"""AgentDiff deterministic proof and delivery for AI-generated changes.

Verified API migration and the underlying trust pipeline are the primary surfaces.
"""

__version__ = "0.4.0"

from .analyzers import FutureBlastEngine, FutureBlastResult
from .cortex import (
    AgentMemoryStore,
    CompressedContextCard,
    ContextCompressor,
    ContextPacker,
    CortexResult,
    CortexRouter,
    MemoryHit,
    RemediationAdvisor,
    RepositoryMemoryProvider,
    SkillCardGenerator,
    SkillContract,
)
from .evidence import CapsuleReader, PatchBundle, PatchEntry, PatchManifest
from .impact import ImpactEngine, ProofCache, ProofCacheEntry, ProofCacheKey
from .integrations import (
    AgentDiffConfig,
    AgentDiffSession,
    BaseAgentDiffAdapter,
    MCPPolicyHook,
    ToolCallBlockedError,
    ToolCallDecision,
)
from .policy import (
    Policy,
    PolicyAction,
    PolicyDecision,
    PolicyEngine,
    ProofPolicy,
    load_policy,
    load_policy_file,
)
from .promotion import (
    PromotionEngine,
    PromotionPlan,
    PromotionRecovery,
    PromotionReport,
    WorkspaceLease,
)
from .proof import ProofEngine, ProofPhaseResult, ProofResult, ProofVerdict
from .providers import (
    AIProvider,
    AnthropicMessagesProvider,
    OllamaChatProvider,
    OllamaEmbeddingProvider,
    OpenAIResponsesProvider,
    ProviderError,
    ProviderResponse,
    create_provider,
)
from .repair import (
    FailurePacket,
    HumanAttentionRouter,
    RepairLoop,
    RepairOutcome,
    RoutingDecision,
)
from .runtime import (
    DockerRuntime,
    LocalRuntime,
    RuntimeBackend,
    RuntimeCapability,
    RuntimeControlLevel,
    RuntimeResult,
    WorkspaceMaterializer,
)
from .safety import ControlLevel, HybridSafetyWatcher, SafetyController, SafetyReport
from .scoring import (
    BlastRadiusResult,
    BlastRadiusScorer,
    BlastRadiusWeights,
    MutationRisk,
    RiskLevel,
)
from .sidecar import (
    Notification,
    Notifier,
    SidecarClient,
    SidecarError,
    WrapRunner,
    WrapSummary,
    ensure_sidecar,
)
from .transaction import (
    AgentRunTransaction,
    RollbackEngine,
    RunInspector,
    RunStore,
    TransactionResult,
)
from .trust import RepoImpactGraph, RepositoryInspection, RepositoryInspector, TrustCompiler
from .workspace import (
    AgentWorkspace,
    BaseWorkspace,
    WarmWorkspaceFactory,
    WorkspaceIdentity,
    compute_identity,
)

__all__ = [
    "AIProvider",
    "AgentDiffConfig",
    "AgentDiffSession",
    "AgentMemoryStore",
    "AgentRunTransaction",
    "AgentWorkspace",
    "AnthropicMessagesProvider",
    "BaseAgentDiffAdapter",
    "BaseWorkspace",
    "BlastRadiusResult",
    "BlastRadiusScorer",
    "BlastRadiusWeights",
    "CapsuleReader",
    "CompressedContextCard",
    "ContextCompressor",
    "ContextPacker",
    "ControlLevel",
    "CortexResult",
    "CortexRouter",
    "DockerRuntime",
    "FailurePacket",
    "FutureBlastEngine",
    "FutureBlastResult",
    "HumanAttentionRouter",
    "HybridSafetyWatcher",
    "ImpactEngine",
    "LocalRuntime",
    "MCPPolicyHook",
    "MemoryHit",
    "MutationRisk",
    "Notification",
    "Notifier",
    "OllamaChatProvider",
    "OllamaEmbeddingProvider",
    "OpenAIResponsesProvider",
    "PatchBundle",
    "PatchEntry",
    "PatchManifest",
    "Policy",
    "PolicyAction",
    "PolicyDecision",
    "PolicyEngine",
    "PromotionEngine",
    "PromotionPlan",
    "PromotionRecovery",
    "PromotionReport",
    "ProofCache",
    "ProofCacheEntry",
    "ProofCacheKey",
    "ProofEngine",
    "ProofPhaseResult",
    "ProofPolicy",
    "ProofResult",
    "ProofVerdict",
    "ProviderError",
    "ProviderResponse",
    "RemediationAdvisor",
    "RepairLoop",
    "RepairOutcome",
    "RepoImpactGraph",
    "RepositoryInspection",
    "RepositoryInspector",
    "RepositoryMemoryProvider",
    "RiskLevel",
    "RollbackEngine",
    "RoutingDecision",
    "RunInspector",
    "RunStore",
    "RuntimeBackend",
    "RuntimeCapability",
    "RuntimeControlLevel",
    "RuntimeResult",
    "SafetyController",
    "SafetyReport",
    "SidecarClient",
    "SidecarError",
    "SkillCardGenerator",
    "SkillContract",
    "ToolCallBlockedError",
    "ToolCallDecision",
    "TransactionResult",
    "TrustCompiler",
    "WarmWorkspaceFactory",
    "WorkspaceIdentity",
    "WorkspaceLease",
    "WorkspaceMaterializer",
    "WrapRunner",
    "WrapSummary",
    "compute_identity",
    "create_provider",
    "ensure_sidecar",
    "load_policy",
    "load_policy_file",
]
