"""Self-Maintaining APIs: AST scanning, breaking change matching, and migration impact."""

from agentdiff.api.intel import (
    ChangelogChange,
    ChangelogParser,
    IntelArtifact,
    ManifestCandidate,
    OpenAPIBreakingChange,
    OpenAPIDiffAnalyzer,
    ProviderIntelEngine,
    SDKReleaseAnalyzer,
    SDKReleaseChange,
)

from agentdiff.api.manifest import (
    AffectedSymbols,
    APIChangeManifest,
    ManifestSource,
    MigrationStrategyConfig,
    MigrationStrategyType,
    ReplacementSymbols,
    SourceType,
    get_builtin_manifest,
    list_builtin_manifests,
)
from agentdiff.api.matcher import APIMatcher
from agentdiff.api.migrate import MigrationEngine
from agentdiff.api.models import (
    APIChange,
    APIUsage,
    ChangeSeverity,
    ChangeType,
    MatchedChange,
    MigrationAssessment,
    MigrationCertificate,
    MigrationConfidence,
    MigrationImpact,
    MigrationPlan,
    MigrationResult,
    MigrationStatus,
    MigrationStrategy,
    VerificationLevel,
    assess_migration_confidence,
)
from agentdiff.api.plugins import (
    ProviderPlugin,
    discover_plugins,
    install_plugin,
    list_plugins,
    load_plugin,
)
from agentdiff.api.providers import (
    APIProvider,
    OpenAIProvider,
    StripeProvider,
    get_all_providers,
    get_provider,
    get_providers_for_selection,
    list_providers,
)
from agentdiff.api.scanner import APIScanner
from agentdiff.api.transforms import (
    OpenAIChatToResponsesTransform,
    OpenAILegacyChatCompletionTransform,
    get_transform,
    get_transforms_for_usage,
    list_transforms,
)
from agentdiff.api.version_detector import (
    SDKVersionInfo,
    detect_installed_sdk_versions,
    is_version_affected,
)

__all__ = [
    "APIChange",
    "APIChangeManifest",
    "APIMatcher",
    "APIProvider",
    "APIScanner",
    "APIUsage",
    "AffectedSymbols",
    "ChangeSeverity",
    "ChangeType",
    "ChangelogChange",
    "ChangelogParser",
    "IntelArtifact",
    "ManifestCandidate",
    "ManifestSource",
    "MatchedChange",
    "MigrationAssessment",
    "MigrationCertificate",
    "MigrationConfidence",
    "MigrationEngine",
    "MigrationImpact",
    "MigrationPlan",
    "MigrationResult",
    "MigrationStatus",
    "MigrationStrategy",
    "MigrationStrategyConfig",
    "MigrationStrategyType",
    "OpenAIChatToResponsesTransform",
    "OpenAILegacyChatCompletionTransform",
    "OpenAIProvider",
    "OpenAPIBreakingChange",
    "OpenAPIDiffAnalyzer",
    "ProviderIntelEngine",
    "ProviderPlugin",
    "ReplacementSymbols",
    "SDKReleaseAnalyzer",
    "SDKReleaseChange",
    "ReplacementSymbols",
    "SDKVersionInfo",
    "SourceType",
    "StripeProvider",
    "VerificationLevel",
    "assess_migration_confidence",
    "detect_installed_sdk_versions",
    "discover_plugins",
    "get_all_providers",
    "get_builtin_manifest",
    "get_provider",
    "get_providers_for_selection",
    "get_transform",
    "get_transforms_for_usage",
    "install_plugin",
    "is_version_affected",
    "list_builtin_manifests",
    "list_plugins",
    "list_providers",
    "list_transforms",
    "load_plugin",
    "is_version_affected",
    "list_builtin_manifests",
    "list_providers",
    "list_transforms",
]
